version: '3.8'

services:
  mosquitto:
    image: iegomez/mosquitto-go-auth
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs/fullchain.pem:/mosquitto/certs/fullchain.pem:ro,z
      - ./mosquitto/certs/privkey.pem:/mosquitto/certs/privkey.pem:ro,z
    networks:
      - mqtt_default
      - mysql_default

networks:
  mqtt_default:
    external: true
  mysql_default:
    external: true
