/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ARCANA_REGISTRATION_PB_H_INCLUDED
#define PB_ARCANA_REGISTRATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) arcana_RegisterRequest_public_key_t;
typedef struct _arcana_RegisterRequest {
    char device_id[16]; /* "32FFD605" (8-char UID hex) */
    arcana_RegisterRequest_public_key_t public_key; /* 64 bytes P-256 raw (x||y) */
    uint32_t firmware_ver; /* e.g. 0x0100 = v1.0 */
} arcana_RegisterRequest;

typedef struct _arcana_RegisterResponse {
    bool success;
    char mqtt_user[32]; /* "dev-32FFD605" */
    char mqtt_pass[32]; /* random 32 chars */
    char mqtt_broker[32]; /* "arcana.boo" */
    uint32_t mqtt_port; /* 1883 */
    char upload_token[64]; /* HMAC signed token */
    char topic_prefix[32]; /* "/arcana/32FFD605" */
    char error[32]; /* error message if !success */
} arcana_RegisterResponse;

typedef PB_BYTES_ARRAY_T(32) arcana_AuthChallenge_nonce_t;
typedef struct _arcana_AuthChallenge {
    arcana_AuthChallenge_nonce_t nonce; /* 32 bytes random from server */
} arcana_AuthChallenge;

typedef PB_BYTES_ARRAY_T(72) arcana_AuthResponse_signature_t;
typedef struct _arcana_AuthResponse {
    char device_id[16];
    arcana_AuthResponse_signature_t signature; /* ECDSA P-256 sign(privateKey, nonce) */
} arcana_AuthResponse;

typedef struct _arcana_AuthResult {
    bool success;
    char upload_token[64]; /* refreshed token */
    char error[32];
} arcana_AuthResult;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define arcana_RegisterRequest_init_default      {"", {0, {0}}, 0}
#define arcana_RegisterResponse_init_default     {0, "", "", "", 0, "", "", ""}
#define arcana_AuthChallenge_init_default        {{0, {0}}}
#define arcana_AuthResponse_init_default         {"", {0, {0}}}
#define arcana_AuthResult_init_default           {0, "", ""}
#define arcana_RegisterRequest_init_zero         {"", {0, {0}}, 0}
#define arcana_RegisterResponse_init_zero        {0, "", "", "", 0, "", "", ""}
#define arcana_AuthChallenge_init_zero           {{0, {0}}}
#define arcana_AuthResponse_init_zero            {"", {0, {0}}}
#define arcana_AuthResult_init_zero              {0, "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define arcana_RegisterRequest_device_id_tag     1
#define arcana_RegisterRequest_public_key_tag    2
#define arcana_RegisterRequest_firmware_ver_tag  3
#define arcana_RegisterResponse_success_tag      1
#define arcana_RegisterResponse_mqtt_user_tag    2
#define arcana_RegisterResponse_mqtt_pass_tag    3
#define arcana_RegisterResponse_mqtt_broker_tag  4
#define arcana_RegisterResponse_mqtt_port_tag    5
#define arcana_RegisterResponse_upload_token_tag 6
#define arcana_RegisterResponse_topic_prefix_tag 7
#define arcana_RegisterResponse_error_tag        8
#define arcana_AuthChallenge_nonce_tag           1
#define arcana_AuthResponse_device_id_tag        1
#define arcana_AuthResponse_signature_tag        2
#define arcana_AuthResult_success_tag            1
#define arcana_AuthResult_upload_token_tag       2
#define arcana_AuthResult_error_tag              3

/* Struct field encoding specification for nanopb */
#define arcana_RegisterRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        2) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_ver,      3)
#define arcana_RegisterRequest_CALLBACK NULL
#define arcana_RegisterRequest_DEFAULT NULL

#define arcana_RegisterResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   mqtt_user,         2) \
X(a, STATIC,   SINGULAR, STRING,   mqtt_pass,         3) \
X(a, STATIC,   SINGULAR, STRING,   mqtt_broker,       4) \
X(a, STATIC,   SINGULAR, UINT32,   mqtt_port,         5) \
X(a, STATIC,   SINGULAR, STRING,   upload_token,      6) \
X(a, STATIC,   SINGULAR, STRING,   topic_prefix,      7) \
X(a, STATIC,   SINGULAR, STRING,   error,             8)
#define arcana_RegisterResponse_CALLBACK NULL
#define arcana_RegisterResponse_DEFAULT NULL

#define arcana_AuthChallenge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    nonce,             1)
#define arcana_AuthChallenge_CALLBACK NULL
#define arcana_AuthChallenge_DEFAULT NULL

#define arcana_AuthResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2)
#define arcana_AuthResponse_CALLBACK NULL
#define arcana_AuthResponse_DEFAULT NULL

#define arcana_AuthResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   upload_token,      2) \
X(a, STATIC,   SINGULAR, STRING,   error,             3)
#define arcana_AuthResult_CALLBACK NULL
#define arcana_AuthResult_DEFAULT NULL

extern const pb_msgdesc_t arcana_RegisterRequest_msg;
extern const pb_msgdesc_t arcana_RegisterResponse_msg;
extern const pb_msgdesc_t arcana_AuthChallenge_msg;
extern const pb_msgdesc_t arcana_AuthResponse_msg;
extern const pb_msgdesc_t arcana_AuthResult_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define arcana_RegisterRequest_fields &arcana_RegisterRequest_msg
#define arcana_RegisterResponse_fields &arcana_RegisterResponse_msg
#define arcana_AuthChallenge_fields &arcana_AuthChallenge_msg
#define arcana_AuthResponse_fields &arcana_AuthResponse_msg
#define arcana_AuthResult_fields &arcana_AuthResult_msg

/* Maximum encoded size of messages (where known) */
#define ARCANA_REGISTRATION_PB_H_MAX_SIZE        arcana_RegisterResponse_size
#define arcana_AuthChallenge_size                34
#define arcana_AuthResponse_size                 91
#define arcana_AuthResult_size                   100
#define arcana_RegisterRequest_size              89
#define arcana_RegisterResponse_size             238

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
