#!/bin/bash
#
# init-cor-afp-ntp.sh
# 初始化 COR + AFP + NTP 工作環境
# 適用於 opencode CLI + kimi Code API 環境
#

set -e

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 參數解析
TASK_NAME="$1"
PROJECT_PATH="${2:-.}"

# 使用說明
usage() {
    echo "Usage: $0 <task-name> [project-path]"
    echo ""
    echo "Example:"
    echo "  $0 \"實作 USART2 DMA 驅動\""
    echo "  $0 \"新增 GPIO 中斷處理\" /path/to/project"
    exit 1
}

# 檢查參數
if [ -z "$TASK_NAME" ]; then
    echo -e "${RED}❌ Error: Task name is required${NC}"
    usage
fi

# 解析絕對路徑
PROJECT_PATH=$(cd "$PROJECT_PATH" 2>/dev/null && pwd || echo "$PROJECT_PATH")
WORKSPACE="$PROJECT_PATH/.cor-afp-ntp"

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Initializing COR-AFP-NTP Workspace${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# 檢查依賴
check_dependencies() {
    local missing=()
    
    if ! command -v jq >/dev/null 2>&1; then
        missing+=("jq")
    fi
    
    if ! command -v uuidgen >/dev/null 2>&1; then
        missing+=("uuidgen")
    fi
    
    if [ ${#missing[@]} -gt 0 ]; then
        echo -e "${RED}❌ Missing dependencies:${NC}"
        printf '   - %s\n' "${missing[@]}"
        echo ""
        echo "Install with:"
        echo "  macOS: brew install jq"
        exit 1
    fi
}

check_dependencies

# 創建目錄結構
echo -e "${YELLOW}📁 Creating workspace structure...${NC}"

mkdir -p "$WORKSPACE"/{checkpoints,00-init,01-analysis,02-design,03-impl,04-validation,05-finalize}

# 生成 session ID 和時間戳
SESSION_ID=$(uuidgen)
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S+08:00")

# 創建 current-process.json
echo -e "${YELLOW}📝 Creating current-process.json...${NC}"

cat > "$WORKSPACE/current-process.json" << EOF
{
  "protocol_version": "1.0.0",
  "session_id": "$SESSION_ID",
  "current_node": "00-init",
  "task_name": "$TASK_NAME",
  "project_path": "$PROJECT_PATH",
  "started_at": "$TIMESTAMP",
  "updated_at": "$TIMESTAMP",
  "token_estimate": 0,
  "completed_nodes": [],
  "node_outputs": {},
  "validation_state": {},
  "recovery_hints": {
    "last_action": "Task initialized",
    "pending_fixes": [],
    "files_modified": [],
    "critical_decisions": []
  },
  "context_window": {
    "estimated_tokens": 0,
    "last_compaction": null,
    "warning_threshold": 80000
  }
}
EOF

# 創建 validation-chain.json
cat > "$WORKSPACE/validation-chain.json" << EOF
{
  "chain": [],
  "last_valid_checkpoint": null
}
EOF

# 創建 phase-summary.md 初始版本
cat > "$WORKSPACE/phase-summary.md" << EOF
# Task: $TASK_NAME

## Initialization

**Session ID**: $SESSION_ID  
**Started**: $TIMESTAMP  
**Status**: 🟡 In Progress

---

## Node Progress

- [ ] 00-init: Initialization
- [ ] 01-analysis: Analysis
- [ ] 02-design: Design
- [ ] 03-impl: Implementation
- [ ] 04-validation: Validation
- [ ] 05-finalize: Finalization

---

*Generated by init-cor-afp-ntp.sh*
EOF

# 創建 00-init 節點檔案
echo -e "${YELLOW}📝 Creating 00-init node files...${NC}"

cat > "$WORKSPACE/00-init/README.md" << 'EOF'
# 00-init: 任務初始化

## 目的
定義任務範圍、識別目標檔案、載入必要參考資料

## 執行步驟

1. **明確任務目標**
   - 理解用戶需求
   - 確認驗收標準
   - 定義完成條件

2. **識別目標檔案**
   - 需要修改的現有檔案
   - 需要建立的新檔案
   - 相關的配置檔案

3. **載入技術參考**
   - 相關的程式碼檔案
   - 技術文件或規格
   - 範例程式碼

4. **確認環境準備**
   - 開發環境就緒
   - 相依套件安裝
   - 編譯工具可用

## 產出物檢查清單

- [ ] requirements.md - 需求說明
- [ ] target-files.json - 目標檔案清單
- [ ] references.md - 參考資料清單

## 完成後

執行驗證：
```bash
bash .cor-afp-ntp/00-init/exit.sh
```

然後轉換到下一節點：
```bash
bash .cor-protocol/scripts/node-transition.sh 00-init 01-analysis
```
EOF

cat > "$WORKSPACE/00-init/checklist.md" << 'EOF'
# 00-init Checklist

## 任務定義
- [ ] 任務目標明確
- [ ] 驗收標準清晰
- [ ] 完成條件定義

## 檔案識別
- [ ] 列出所有需要修改的檔案
- [ ] 列出所有需要建立的檔案
- [ ] 確認檔案路徑正確

## 參考資料
- [ ] 載入相關程式碼
- [ ] 載入技術文件
- [ ] 記錄關鍵參考連結

## 環境確認
- [ ] 開發環境正常
- [ ] 編譯工具可用
- [ ] 相依套件安裝完成
EOF

cat > "$WORKSPACE/00-init/exit.sh" << 'EOF'
#!/bin/bash
#
# 00-init Exit Validation Script
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$(dirname "$SCRIPT_DIR")"
CURRENT_NODE="00-init"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  NTP Exit Validation: $CURRENT_NODE${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

ERRORS=()
WARNINGS=()

# Check 1: requirements.md
if [ ! -f "$WORKSPACE/$CURRENT_NODE/requirements.md" ]; then
    ERRORS+=("❌ requirements.md not found")
else
    echo -e "${GREEN}✅ requirements.md exists${NC}"
fi

# Check 2: target-files.json
if [ ! -f "$WORKSPACE/$CURRENT_NODE/target-files.json" ]; then
    ERRORS+=("❌ target-files.json not found")
else
    echo -e "${GREEN}✅ target-files.json exists${NC}"
    
    # Validate JSON structure
    if ! jq empty "$WORKSPACE/$CURRENT_NODE/target-files.json" 2>/dev/null; then
        ERRORS+=("❌ target-files.json is invalid JSON")
    else
        echo -e "${GREEN}✅ target-files.json is valid JSON${NC}"
    fi
fi

# Check 3: references.md (optional but recommended)
if [ ! -f "$WORKSPACE/$CURRENT_NODE/references.md" ]; then
    WARNINGS+=("⚠️  references.md not found (optional but recommended)")
else
    echo -e "${GREEN}✅ references.md exists${NC}"
fi

# Output results
echo ""
if [ ${#ERRORS[@]} -eq 0 ] && [ ${#WARNINGS[@]} -eq 0 ]; then
    echo -e "${GREEN}✅ All validation checks passed!${NC}"
    echo ""
    echo "Ready to transition to next node."
    echo "Run: bash .cor-protocol/scripts/node-transition.sh 00-init 01-analysis"
    exit 0
else
    if [ ${#ERRORS[@]} -gt 0 ]; then
        echo -e "${RED}❌ Validation failed with ${#ERRORS[@]} error(s):${NC}"
        printf '%s\n' "${ERRORS[@]}"
    fi
    
    if [ ${#WARNINGS[@]} -gt 0 ]; then
        echo ""
        echo -e "${YELLOW}⚠️  Warnings (${#WARNINGS[@]}):${NC}"
        printf '%s\n' "${WARNINGS[@]}"
    fi
    
    echo ""
    echo "Please fix the errors before proceeding."
    exit 1
fi
EOF

chmod +x "$WORKSPACE/00-init/exit.sh"

# 創建其他節點的範本結構
for node in 01-analysis 02-design 03-impl 04-validation 05-finalize; do
    NODE_DIR="$WORKSPACE/$node"
    NODE_NAME=$(echo "$node" | cut -d'-' -f2)
    
    cat > "$NODE_DIR/README.md" << EOF
# $node: $(echo "$NODE_NAME" | sed 's/.*/\u&/')

## 目的
[待填寫：此節點的目的]

## 執行步驟
1. [步驟 1]
2. [步驟 2]
3. [步驟 3]

## 產出物
- [ ] [產出物 1]
- [ ] [產出物 2]

## 完成後
執行驗證：
\`\`\`bash
bash .cor-afp-ntp/$node/exit.sh
\`\`\`
EOF

    cat > "$NODE_DIR/checklist.md" << EOF
# $node Checklist

- [ ] [檢查項目 1]
- [ ] [檢查項目 2]
- [ ] [檢查項目 3]
EOF

    cat > "$NODE_DIR/exit.sh" << 'EOF'
#!/bin/bash
#
# Exit Validation Script
#

WORKSPACE="$(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd))"
CURRENT_NODE="$(basename $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd))"

echo "Exit validation for $CURRENT_NODE"
echo "Customize this script for specific validation checks"

# TODO: Add specific validation checks

echo "✅ Validation passed"
exit 0
EOF

    chmod +x "$NODE_DIR/exit.sh"
done

# 輸出完成訊息
echo ""
echo -e "${GREEN}✅ COR-AFP-NTP workspace initialized successfully!${NC}"
echo ""
echo -e "${BLUE}Workspace:${NC} $WORKSPACE"
echo -e "${BLUE}Session ID:${NC} $SESSION_ID"
echo -e "${BLUE}Task:${NC} $TASK_NAME"
echo ""
echo -e "${YELLOW}📋 Next Steps:${NC}"
echo ""
echo "1. Read the protocol guide:"
echo "   cat .cor-protocol/OPENCODE_KIMI_EXECUTION_PROTOCOL.md"
echo ""
echo "2. Start with the first node:"
echo "   cat .cor-afp-ntp/00-init/README.md"
echo ""
echo "3. After completing the node, run:"
echo "   bash .cor-afp-ntp/00-init/exit.sh"
echo ""
echo "4. Transition to next node:"
echo "   bash .cor-protocol/scripts/node-transition.sh 00-init 01-analysis"
echo ""
