/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "registration.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(arcana_RegisterRequest, arcana_RegisterRequest, AUTO)


PB_BIND(arcana_RegisterResponse, arcana_RegisterResponse, 2)


PB_BIND(arcana_AuthChallenge, arcana_AuthChallenge, AUTO)


PB_BIND(arcana_AuthResponse, arcana_AuthResponse, AUTO)


PB_BIND(arcana_AuthResult, arcana_AuthResult, AUTO)



