per_listener_settings false
allow_anonymous false
retain_available false

# Plain MQTT (for local/dev — remove in production)
listener 1883 0.0.0.0
protocol mqtt

# MQTTS (TLS)
listener 8883 0.0.0.0
protocol mqtt
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem

# WSS (WebSocket over TLS)
listener 9001 0.0.0.0
protocol websockets

auth_plugin /mosquitto/go-auth.so
auth_opt_log_level debug
auth_opt_backends mysql
auth_opt_mysql_hasher bcrypt
auth_opt_mysql_host mysql
auth_opt_mysql_port 3306
auth_opt_mysql_user root
auth_opt_mysql_password 5YzYziFT3g
auth_opt_mysql_dbname mqtt
auth_opt_mysql_userquery select password_hash from user where username = ? limit 1
auth_opt_mysql_aclquery SELECT a.topic FROM user u, acl a WHERE (a.user_id = u.id) AND u.username=? AND a.rw = ?
